### ISSUE TITLE
setup Google App Scripts for automatically create milestone

### ISSUE THREAD

**Issue by hidecharo** [hidecharo/issue-manager-by-nuxt#2]
- [ ] open Google Drive and create gas
- [ ] write code (use already created)
- [ ] set trigger weekly
